---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: enn-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enn-policy
subjects:
- kind: ServiceAccount
  name: enn-policy
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: enn-policy
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - endpoints
      - services
      - nodes
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enn-policy
  namespace: kube-system
---
apiVersion: v1
data:
  kubeconfig.conf: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://10.19.138.96:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  labels:
    app: enn-policy
  name: enn-policy

  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: enn-policy
  namespace: kube-system
  labels:
    app: enn-policy
spec:
  template:
    metadata:
      labels:
        name: enn-policy
    spec:
      hostNetwork: true
      serviceAccountName: enn-policy
      containers:
      - name: enn-policy
        image: xujieasd/enn-policy:xx.xx
        imagePullPolicy: IfNotPresent
        args:
          - "--kubeconfig=/var/lib/enn-policy/kubeconfig.conf"
          - "--logtostderr=false"
#          - "--ip-range=10.244.0.0/16"
          - "--v=7"
          - "--log-dir=/var/log/enn-policy"
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
            readOnly: true
          - mountPath: /var/lib/enn-policy
            name: kubeconfig
          - mountPath: /var/log/enn-policy
            name: logfile
      volumes:
        - name: lib-modules
          hostPath:
              path: /lib/modules
        - name: kubeconfig
          configMap:
              name: enn-policy
        - name: logfile
          hostPath:
              path: /var/log/enn-policy


